#!/bin/bash

source "$CONFIG_DIR/colors.sh"

# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$CONFIG_DIR/plugins"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar position=top height=40 blur_radius=10 #color=$BAR_COLOR 

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  padding_left=5
  padding_right=5
  icon.font="Hack Nerd Font:Regular:15.0"
  label.font="SF Pro:Semibold:15.0"
  icon.color=$WHITE
  label.color=$WHITE
  icon.padding_left=10
  icon.padding_right=0
  label.padding_left=10
  label.padding_right=10
  background.color=$ITEM_BG_COLOR
  background.corner_radius=5
  background.height=24
)
sketchybar --default "${default[@]}"

##### Adding Mission Control Space Indicators #####
# Let's add some mission control spaces:
# https://felixkratz.github.io/SketchyBar/config/components#space----associate-mission-control-spaces-with-an-item
# to indicate active and available mission control spaces.

# SPACE_ICONS=("1" "2" "3" "4" "5" "6" "7" "8" "9" "10")
# for i in "${!SPACE_ICONS[@]}"
# do
#   sid="$(($i+1))"
#   space=(
#     space="$sid"
#     icon="${SPACE_ICONS[i]}"
#     icon.padding_left=7
#     icon.padding_right=7
#     background.color=0x40ffffff
#     background.corner_radius=5
#     background.height=25
#     label.drawing=off
#     script="$PLUGIN_DIR/space.sh"
#     click_script="yabai -m space --focus $sid"
#   )
#   sketchybar --add space space."$sid" left --set space."$sid" "${space[@]}"
# done
#
##### Adding Left Items #####
# We add some regular items to the left side of the bar, where
# only the properties deviating from the current defaults need to be set

sketchybar --add item apple left \
           --set apple icon= label.drawing=off icon.padding_right=10 \
           --add item front_app left \
           --set front_app icon.drawing=off script="$PLUGIN_DIR/front_app.sh"  \
           --subscribe front_app front_app_switched


sketchybar --add event aerospace_workspace_change

sketchybar --add item window_title left \
           --set window_title icon=\
                               label.font="SF Pro:Semibold:14.0" \
                               icon.padding_left=0 \
                               width=dynamic \
                               updates=on \
                               update_freq=1 \
                               script="$PLUGIN_DIR/aerospace_window_title.sh" \
          --subscribe window_title aerospace_workspace_change

##### Adding Right Items #####
# In the same way as the left items we can add items to the right side.
# Additional position (e.g. center) are available, see:
# https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar

# sketchybar --add item calendar right \
#             --set calendar icon=􀉉 \ 
#                           label="$(date +'%a %d %b %I:%M %p')"

# Some items refresh on a fixed cycle, e.g. the clock runs its script once
# every 10s. Other items respond to events they subscribe to, e.g. the
# volume.sh script is only executed once an actual change in system audio
# volume is registered. More info about the event system can be found here:
# https://felixkratz.github.io/SketchyBar/config/events

sketchybar --add item clock right \
           --set clock update_freq=10 icon=􀉉  script="$PLUGIN_DIR/clock.sh" \
           --add item volume right \
           --set volume script="$PLUGIN_DIR/volume.sh" padding_right=4 \
           --subscribe volume volume_change \
           --add item battery right \
           --set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" padding_right=4 \
           --subscribe battery system_woke power_source_change

sketchybar --add item spotify right \
           --set spotify script="$PLUGIN_DIR/spotify.sh" \
                         label.padding_left=0 \
                         icon.padding_right=8 \
                         icon= \
                         click_script="open -a Spotify" \ 
                         drawing=off \
           --subscribe spotify media_change



##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update



sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$(aerospace list-workspaces --focused)
